name: "Level 1"
map_dir: './assets/'
screen_width: 1024
screen_height: 1024
line:
  thickness: 2
FRAME_PER_SECONDS: 60
view:
  hider: 2
  seeker: 3
amount:
  hider: 10
  seeker: 1
moveable:
  hider: False
  seeker: True
pushable:
  hider: False
  seeker: False

